# Generated by Django 6.0.5 on 2026-05-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='TechPro Engineering', max_length=200)),
                ('tagline', models.CharField(default='Powering the Future with Precision Engineering', max_length=300)),
                ('email', models.EmailField(default='info@techpro.com', max_length=254)),
                ('phone', models.CharField(default='+237690000000', max_length=30)),
                ('whatsapp', models.CharField(default='+237690000000', max_length=30)),
                ('address', models.TextField(default='Bamenda, Cameroon')),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('years_experience', models.PositiveIntegerField(default=10)),
                ('projects_completed', models.PositiveIntegerField(default=500)),
                ('happy_clients', models.PositiveIntegerField(default=300)),
                ('team_members', models.PositiveIntegerField(default=25)),
                ('about_text', models.TextField(blank=True)),
                ('mission_text', models.TextField(blank=True)),
                ('vision_text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
