# Generated by Django 6.0.4 on 2026-06-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_member_social_handles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='bi-patch-check-fill', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=350)),
                ('image', models.ImageField(upload_to='banners/')),
                ('button_text', models.CharField(default='Request a Quote', max_length=120)),
                ('button_url', models.CharField(default='/contact/', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Banner',
                'verbose_name_plural': 'Homepage Banners',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='about_heading',
            field=models.CharField(default='Building Reliable Energy and Electrical Infrastructure', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_text',
            field=models.CharField(default='Request a Free Quote', max_length=120),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_cta_url',
            field=models.CharField(default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_heading',
            field=models.CharField(default='Reliable Engineering and Solar Energy', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_subtitle',
            field=models.CharField(default='We are a Bamenda-based engineering and electrical solutions company committed to delivering reliable, high-quality, and innovative services. Through professionalism, technical expertise, and customer-centered solutions, we continue to build trust and satisfaction while growing our presence across the region.', max_length=350),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='values_intro',
            field=models.TextField(blank=True, default='Our values reflect our promise to deliver reliable solutions, professional workmanship, and customer-focused outcomes on every project.'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default='We deliver reliable solar, electrical, security, and construction support solutions from our Bamenda base.'),
        ),
    ]
