# Generated by Django 6.0.4 on 2026-06-01 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corevalue_homepagebanner_sitesettings_about_heading_and_more'),
        ('core', '0003_homepage_content'),
    ]

    operations = [
    ]
